apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.game.service.name }}
spec:
  # type: ClusterIP
  selector:
    app: {{ .Values.game.app.selectorLabel }} 
  ports:
    - protocol: {{ .Values.game.service.ports.protocol }} 
      port: {{ .Values.game.service.ports.port }} 
      targetPort: {{ .Values.game.service.ports.targetPort }} 
