apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.game.service.name }}
  namespace: {{ .Values.game.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.game.app.selectorLabel }} 
  ports:
    - protocol: {{ .Values.game.service.protocol }} 
      port: {{ .Values.game.service.port }} 
      targetPort: {{ .Values.game.service.targetPort }} 
      nodePort: {{ .Values.game.service.nodePort }} 
