apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: app-ingress
spec:
  ingressClassName: nginx 
  rules:
    - host: {{ .Values.game.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: {{ .Values.game.service.name }}
                port: 
                    number: {{ .Values.game.service.ports.targetPort }}