game:
  name: game

  image:
    containerName: "mario-container"
    repository: "nirmalnaveen/supermario"
    tag: "latest"
    pullPolicy: Always

  ports:
    containerPort: 80

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

