game:
  name: game

  service: 
    name: "mario-deployment"
    ports:
      protocol: TCP
      port: 80
      targetPort: 80

  deployment: 
    name: "mario-deployment"
  app: 
    selectorLabel: "mario" 
  image:
    containerName: "mario-container"
    repository: "nirmalnaveen/supermario"
    tag: "latest"
    pullPolicy: Always
    ports:
      containerPort: 80
      nodePort: 80

  ingress:
    host: first-order-ai.brewsentry.com
    
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

