game:
  name: game

  image:
    repository: "nirmalnaveen/supermario"
    tag: "latest"
    pullPolicy: Always

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

