name: Terraform Manual Deploy

on:
  workflow_dispatch:


jobs:
  terraform:
    env:
      AWS_REGION: us-east-1
      
    name: Terraform Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /usr/local/bin
          eksctl version


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Allow GitHub Actions in EKS Public Access CIDRs
        run: |
          GITHUB_IPS=$(curl -s https://api.ipify.org )
          eksctl utils update-cluster-vpc-config \
            --cluster smarthire \
            --region us-east-1 \
            --public-access-cidrs "${GITHUB_IPS}/32" \
            --approve || true

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/infrastructure

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform/infrastructure

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/infrastructure
